#ifndef TYPES_H
#define TYPES_H

#include <optional>
#include <QDateTime>
#include <QString>
#include <QUuid>

enum class Button {Start, Pause, Stop};

enum class LockEvent {None, Unlock, Lock, LongOngoingLock};

enum class DurationType { Activity, Pause };

/**
 * Opaque, immutable segment identity.
 *
 * SegmentId wraps a UUID string to prevent empty-string IDs from
 * propagating undetected.  fromString() asserts non-empty in debug
 * builds; mint() always produces a fresh non-empty UUID.
 *
 * The default constructor produces an empty SegmentId (used when no
 * segment is active, e.g. Mode::None in Timer).
 */
class SegmentId {
public:
    SegmentId() = default;

    static SegmentId mint() {
        return SegmentId(QUuid::createUuid().toString(QUuid::WithoutBraces));
    }

    static SegmentId fromString(const QString& s) {
        Q_ASSERT_X(!s.isEmpty(), "SegmentId::fromString", "segment_id must not be empty");
        return SegmentId(s);
    }

    bool isEmpty() const { return value_.isEmpty(); }
    const QString& toString() const { return value_; }

    bool operator==(const SegmentId& o) const { return value_ == o.value_; }
    bool operator!=(const SegmentId& o) const { return value_ != o.value_; }
    bool operator<(const SegmentId& o) const { return value_ < o.value_; }

private:
    explicit SegmentId(const QString& s) : value_(s) {}
    QString value_;
};

inline bool isCrossMidnight(const QDateTime& a, const QDateTime& b);

/// Reason a TimeDuration::create() call was rejected.
/// Returned in DurationCreateResult::error; None means creation succeeded.
enum class DurationCreateError {
    None,             ///< No error — creation succeeded.
    InvalidTimestamp, ///< start or end is not a valid QDateTime.
    NonPositive,      ///< duration is zero or negative (end <= start).
    CrossMidnight     ///< start.date() != end.date() (same-day invariant violated).
};

struct TimeDuration {
    SegmentId segment_id;
    DurationType type;
    qint64 duration;
    QDateTime startTime;
    QDateTime endTime;

    static SegmentId createSegmentId() { return SegmentId::mint(); }

    // Factory: returns a typed result whose error field names the rejection reason.
    // On success, error == DurationCreateError::None and duration is populated.
    struct CreateResult;
    static CreateResult create(DurationType type, QDateTime start, QDateTime end,
                               SegmentId segmentId = SegmentId{});

    // For rows loaded from the DB: already validated and persisted; cross-midnight rows
    // are preserved as-is without re-running the same-day guard.
    static TimeDuration fromPersistedRow(DurationType type, QDateTime start, QDateTime end,
                                         SegmentId segmentId = SegmentId{})
    {
        return TimeDuration(type, start, end, std::move(segmentId));
    }

    // For an in-flight segment snapshot generated by the engine: start/end come from live
    // session state whose validity is guaranteed by Timer's own invariants.
    static TimeDuration fromLiveSession(DurationType type, QDateTime start, QDateTime end,
                                        SegmentId segmentId = SegmentId{})
    {
        return TimeDuration(type, start, end, std::move(segmentId));
    }

private:
    // Raw constructor — bypasses create()'s validation guards (same-day, positive duration).
    // Called only by the static factories (fromPersistedRow, fromLiveSession, create).
    explicit TimeDuration(DurationType type, QDateTime start, QDateTime end, SegmentId segmentId = SegmentId{})
        : segment_id(segmentId.isEmpty() ? SegmentId::mint() : std::move(segmentId)),
          type(type), duration(start.msecsTo(end)), startTime(start), endTime(end) {
    }

};

/// Result of TimeDuration::create().
/// Check has_value() (or error == DurationCreateError::None) for success.
struct TimeDuration::CreateResult {
    std::optional<TimeDuration> duration; ///< Populated on success.
    DurationCreateError error = DurationCreateError::None;

    bool has_value() const { return duration.has_value(); }
    TimeDuration& value()  { return *duration; }
    const TimeDuration& value() const { return *duration; }
    TimeDuration* operator->() { return &*duration; }
    const TimeDuration* operator->() const { return &*duration; }
    TimeDuration& operator*() { return *duration; }
    const TimeDuration& operator*() const { return *duration; }
};

inline TimeDuration::CreateResult TimeDuration::create(DurationType type, QDateTime start, QDateTime end,
                                                       SegmentId segmentId)
{
    if (!start.isValid() || !end.isValid())
        return {{}, DurationCreateError::InvalidTimestamp};
    if (start.msecsTo(end) <= 0)
        return {{}, DurationCreateError::NonPositive};
    if (isCrossMidnight(start, end))
        return {{}, DurationCreateError::CrossMidnight};
    return {TimeDuration(type, start, end, std::move(segmentId)), DurationCreateError::None};
}

inline bool isCrossMidnight(const QDateTime& a, const QDateTime& b) { return a.date() != b.date(); }

/**
 * Tri-state result for hasEntriesForDate.
 *
 * Distinguishes between "definitely no entries" (safe to add boot time)
 * and "we don't know" (history disabled or DB inaccessible — never add
 * boot time to avoid double-counting).
 *
 * - Yes:     Finalized entries exist for the given date.
 * - No:      The DB was queried successfully and zero entries were found.
 * - Unknown: The DB could not be queried (history disabled or open failed).
 */
enum class EntriesForDateResult { Yes, No, Unknown };

#endif // TYPES_H
